# HTTP Server
server:
    port: 8088

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: java
        password: 19-FlemanticO-02
        url: jdbc:mysql://localhost:3306/amy_security?useSSL=false
    jpa:
        database: MYSQL
        show-sql: true
        generate-ddl: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
                dll-auto: true
    main:
        banner-mode: off
    output:
        ansi:
            enabled: ALWAYS
jwt:
    secret: secret
    expiration: 36000

##TODO
##ver porque da error
##spring.jpa.hibernate.naming.physical-strategy=org.hibernate.cfg.ImprovedNamingStrategy
