#----------------------------------------------------------------------------------------------------------------------------------------
#SERVER
server:
    port: 8030

spring:
    profiles: default
    application:
        name: server_gateway
#    main:
#        banner-mode: off
#    output:
#        ansi:
#            enabled: ALWAYS
    cloud:
        gateway:
            routes:
            
            - id: server_security
              #uri: http://localhost:8020/
              uri: lb://server_security
              predicates:
              - Path=/oauth/**
              #filters:
              #- RewritePath=/oauth/, /
              
            - id: service_person
              uri: http://localhost:8101/
              predicates:
              - Path=/person/**
              filters:
              - RewritePath=/person/, /
              
            - id: service_product
              uri: http://localhost:8102/
              predicates:
              - Path=/product/**
              filters:
              - RewritePath=/product/, /
              
            - id: service_sales
              uri: http://localhost:8103/
              predicates:
              - Path=/sales/**
              filters:
              - RewritePath=/sales/, /
              
            - id: service_shopping
              uri: http://localhost:8104/
              predicates:
              - Path=/shopping/**
              filters:
              - RewritePath=/shopping/, /
              
            - id: service_stock
              uri: http://localhost:8105/
              predicates:
              - Path=/stock/**
              filters:
              - RewritePath=/stock/, /


#----------------------------------------------------------------------------------------------------------------------------------------
#EUREKA
eureka:
    client:
        #No registrarse
        register-whit-eureka: true
        #Obtener entradas de registro
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8010/eureka/
    #ver si esto sirve
    instance:
        instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

#----------------------------------------------------------------------------------------------------------------------------------------
#RIBBON No es necesario, se incluye la dependencia automáticamente desde eureka y se asignan las ip:port
#service_security:
#    ribbon:
#        listOfServers: localhost:8103, localhost:8104
#ribbon:
#    eureka:
#        enabled: true
#    connect:
#        timeout: 60000
#    read:
#        timeout: 60000

#Configuración para el log ---------------------------------------------------------------------------------------------------------------------


#----------------------------------------------------------------------------------------------------------------------------------------
#LOG
#%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN: -%5p} %m%n
#%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n
#Default
#%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}
#logging:
#    pattern:
#        console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN: -%5p} %m%n"

#----------------------------------------------------------------------------------------------------------------------------------------
#TODO
